# This file defines how telemetry files are to be identified and
# paired with a process that can import the file

# Top-level directory to look for incoming files
# no longer needed, this will be an arg to the timestamp validator
# import_path: '/Users/JuliaChen/Desktop/xgds/v3_pass8_hercules'

# Registry of regex patterns to look for and what to do when files match them
registry:
  - name: 'RODO'
    filepath_pattern: 'RODO/.*\.csv'
    from: 'csv'
    column_name: '#time'
    format: 'seconds'
    ignore: true
  - name: 'MAPS pose'
    filepath_pattern: 'MAPS/localizations_xgds.txt'
    from: 'csv'
    column_number: 0
    delimiter: ' '
    format: 'iso8601'
  - name: 'MAPS distance'
    filepath_pattern: 'MAPS/distances\.txt'
    from: 'csv'
    column_number: 0
    delimiter: ' '
    format: 'iso8601'
  - name: 'TILT'
    filepath_pattern: 'TILT/[\d\-\.]+_TILT\.csv'
    from: 'csv'
    column_number: 0
    format: 'microseconds'
  - name: 'LGHT'
    filepath_pattern: 'LGHT/[\d\-\.]+_LGHT\.csv'
    from: 'csv'
    column_number: 0
    format: 'microseconds'
  - name: 'MAPS jpg'
    filepath_pattern: 'MAPS/[\d\-\.]+_pc\.jpg'
    from: 'filename'
    format: 'seconds'
  - name: 'NRVS'
    filepath_pattern: 'NRVS/[\d]*_NRVS_[LS]W.*\.csv'
    from: 'csv'
    column_name: 'Epoch Time'
    format: 'seconds'
  - name: 'NRVS'
    filepath_pattern: 'NRVS/NIRVSS_[LS]W[\d\w_]*\.csv'
    from: 'csv'
    column_name: 'Epoch Time'
    format: 'seconds'
  - name: 'NRVD'
    filepath_pattern: 'NRVD/DOC[\dx_OFF]*\.png$'
    from: 'doc'
  - name: 'SLRL'
    filepath_pattern: 'SLRL/[\d\-\.]+_SLRL_.+\.(?i)(JPE?G)'
    from: 'filename'
    format: 'microseconds'
  - name: 'SLRR'
    filepath_pattern: 'SLRR/[\d\-\.]+_SLRR_.+\.(?i)(JPE?G)'
    from: 'filename'
    format: 'microseconds'
  - name: 'MAPS mesh'
    filepath_pattern: 'MAPS/[\d\-\.]+_pc_mesh\.ply'
    from: 'filename'
    format: 'seconds'
  - name: 'MAPS points'
    filepath_pattern: 'MAPS/[\d\-\.]+_(pc|sfm)\.txt'
    ignore: true
  - name: 'NavCam'
    filepath_pattern: 'NAV[LR]/RPCam(0|1)-\d+\.\d+\.tiff$'
  - name: 'RGBD Camera'
    filepath_pattern: 'r-[\d\.]+\.ppm'
  - name: 'RGBD PointCloud'
    filepath_pattern: 'd-[\d\.]+\.pcd'
  - name: 'RGBD Depth'
    filepath_pattern: 'd-[\d\.]+\.pgm'
  - name: 'Resource forks'
    filepath_pattern: '/\._'
    ignore: true
  - name: 'DS Store'
    filepath_pattern: '/\.?_?DS_Store'
    ignore: true
  - name: 'DSLR Raw file'
    filepath_pattern: 'SLR./[\d\w]*\.(?i)(CR)2$'
    ignore: true
  - name: 'WallCam raw data'
    filepath_pattern: 'wallcam_pcds/[\d\.]*\.pcd'
    ignore: true
  - name: 'CeilCam raw data'
    filepath_pattern: 'ceilcam_pcds/[\d\.]*\.pcd'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'graph_xyzrpy.jpg'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'localizations_ixyzm.txt'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'localizations_xyz.txt'
    ignore: true
  - name: 'MAPS mosaic'
    filepath_pattern: 'MAPS/ply_list_drg_(side|top).tif'
    ignore: true
  - name: 'Debug map'
    filepath_pattern: 'MAPS/ply_list_drg_(side|top)_xgds.tif'
    ignore: true
  - name: 'ROS bag file'
    filepath_pattern: '.*\.bag'
    ignore: true
  - name: 'RTI DDS log file'
    filepath_pattern: 'rtiLog'
    ignore: true
  - name: 'Mapping match debug file'
    filepath_pattern: 'MAPS/[\d\._]+_match\.(?i)(txt|jpg)'
    ignore: true
  - name: 'Mapping transform debug file'
    filepath_pattern: 'MAPS/[\d\.]+_transform.txt'
    ignore: true
  - name: 'Mapping output debug file'
    filepath_pattern: 'MAPS/[pointplytransformation]+_list.txt'
    ignore: true
