# This file defines how telemetry files are to be identified and
# paired with a process that can import the file

# Top-level directory to look for incoming files
import_path: '/Users/JuliaChen/Desktop/xgds/v3_pass8_hercules'

# Registry of regex patterns to look for and what to do when files match them
registry:
  - name: 'KRex Track'
    filepath_pattern: '[\d\.]+_RODO.csv'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'Processed KRex Track'
    filepath_pattern: 'MAPS/localizations_xgds.txt'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'KRex Wall Distance'
    filepath_pattern: 'MAPS/distances\.txt'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'Instrument Platform Tilt'
    filepath_pattern: 'TILT/[\d\-\.]+_TILT\.csv'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'Lights'
    filepath_pattern: 'LGHT/[\d\-\.]+_LGHT\.csv'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'Cave wall mosaic'
    filepath_pattern: 'MAPS/ply_list_drg_(side|top).tif'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--camera WallCam %(filename)s'
  - name: '3D Mapping image files'
    filepath_pattern: 'MAPS/wallcam_pcds/[\d\-\.]+_pc\.jpg'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_filename.py'
    arguments: '-t seconds'
  - name: 'NIRVSS Spectrometer'
    filepath_pattern: 'NRVS/[\d]*_NRVS_[LS]W.*\.ascii.csv'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'NIRVSS Spectrometer'
    filepath_pattern: 'NRVS/NIRVSS_[LS]W[\d\w_]*\.csv'
    timestamp_extractor: 'python /Users/JuliaChen/Desktop/xgds/timestamp_extractor_csv.py'
    arguments: '-c Epoch\ Time -d tab -t seconds'
  - name: 'NIRVSS DOC'
    filepath_pattern: 'NRVD/DOC[\dx_OFF]*\.png$'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/importDocImage.py'
  - name: 'SLR Stereo - Left'
    filepath_pattern: 'SLRL/[\d\-\.]+_SLRL_.+\.(?i)(JPE?G)'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--camera SLRL %(filename)s'
  - name: 'SLR Stereo - Right'
    filepath_pattern: 'SLRR/[\d\-\.]+_SLRR_.+\.(?i)(JPE?G)'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--camera SLRR %(filename)s'
  - name: '3D Mapping mesh'
    filepath_pattern: 'MAPS/[\d\-\.]+_pc_mesh\.ply'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_file.py'
    arguments: '--instrument WallCam %(filename)s'
  - name: '3D Mapping point cloud'
    filepath_pattern: 'MAPS/[\d\-\.]+_(pc|sfm)\.txt'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_file.py'
    arguments: '--instrument WallCam %(filename)s'
  - name: 'NavCam'
    filepath_pattern: 'NAV[LR]/HazCam[\d\-\.]+\.TIFF'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--navcam %(filename)s'
  - name: 'RGBD Camera'
    filepath_pattern: 'r-[\d\.]+\.ppm'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--camera RGBD %(filename)s'
  - name: 'RGBD PointCloud'
    filepath_pattern: 'd-[\d\.]+\.pcd'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/dummy_importer.py'
    arguments: '--rgbdpc %(filename)s'
  - name: 'RGBD Depth'
    filepath_pattern: 'd-[\d\.]+\.pgm'
    importer: '/home/xgds/xgds_braille/apps/xgds_braille_app/importer/import_image.py'
    arguments: '--camera RGBD %(filename)s'
  - name: 'Resource forks'
    filepath_pattern: '/\._'
    ignore: true
  - name: 'DS Store'
    filepath_pattern: '/\.?_?DS_Store'
    ignore: true
  - name: 'DSLR Raw file'
    filepath_pattern: 'SLR./[\d\w]*\.(?i)(CR)2$'
    ignore: true
  - name: 'RPCam file'
    filepath_pattern: 'RPCam.*\.tiff'
    ignore: true
  - name: 'WallCam raw data'
    filepath_pattern: 'wallcam_pcds/[\d\.]*\.pcd'
    ignore: true
  - name: 'CeilCam raw data'
    filepath_pattern: 'ceilcam_pcds/[\d\.]*\.pcd'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'graph_xyzrpy.jpg'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'localizations_ixyzm.txt'
    ignore: true
  - name: 'Mapping files we should ignore'
    filepath_pattern: 'localizations_xyz.txt'
    ignore: true
  - name: 'Debug map'
    filepath_pattern: 'MAPS/ply_list_drg_(side|top)_xgds.tif'
    ignore: true
  - name: 'ROS bag file'
    filepath_pattern: '.*\.bag'
    ignore: true
  - name: 'RTI DDS log file'
    filepath_pattern: 'rtiLog'
    ignore: true
  - name: 'Mapping match debug file'
    filepath_pattern: 'MAPS/[\d\._]+_match\.(?i)(txt|jpg)'
    ignore: true
  - name: 'Mapping transform debug file'
    filepath_pattern: 'MAPS/[\d\.]+_transform.txt'
    ignore: true
  - name: 'Mapping output debug file'
    filepath_pattern: 'MAPS/[pointplytransformation]+_list.txt'
    ignore: true
